#!/usr/bin/env bash
# @okf-doc: /commit-hooks.md
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$repo_root"

git rev-parse --absolute-git-dir >/dev/null 2>&1 || {
    echo "install-commit-hooks: repository is not initialized with git" >&2
    exit 1
}

if hooks_path=$(git config --get core.hooksPath); then
    echo "install-commit-hooks: core.hooksPath is already set to $hooks_path" >&2
    echo "refusing to bypass or replace the existing hook configuration" >&2
    exit 1
fi
if ! command -v prek >/dev/null 2>&1; then
    echo "install-commit-hooks: prek is missing; run scripts/setup-build-deps.sh" >&2
    exit 1
fi
prek validate-config prek.toml

# Git uses the common hooks directory in linked worktrees too.
hooks_dir=$(git rev-parse --path-format=absolute --git-path hooks)
hook="$hooks_dir/commit-msg"
bootstrap_marker="# Generated by rust-project-bootstrap install-commit-hooks."
prek_marker="# File generated by prek: https://github.com/j178/prek"

if [[ -e $hook || -L $hook ]]; then
    if [[ -L $hook || ! -f $hook ]] || \
        ! grep -Fqx -e "$bootstrap_marker" -e "$prek_marker" "$hook"; then
        echo "install-commit-hooks: refusing to overwrite existing hook: $hook" >&2
        exit 1
    fi
fi

# --overwrite also deletes this file; never discard a user's legacy hook.
if [[ -e $hook.legacy || -L $hook.legacy ]]; then
    echo "install-commit-hooks: refusing to remove existing hook: $hook.legacy" >&2
    exit 1
fi

exec prek install --config prek.toml --hook-type commit-msg --overwrite
