#!/usr/bin/env bash
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$repo_root"

git_dir=$(git rev-parse --absolute-git-dir 2>/dev/null) || {
    echo "install-commit-hooks: repository is not initialized with git" >&2
    exit 1
}

hooks_path=$(git config --get core.hooksPath || true)
if [[ -n $hooks_path ]]; then
    echo "install-commit-hooks: core.hooksPath is already set to $hooks_path" >&2
    echo "refusing to bypass or replace the existing hook configuration" >&2
    exit 1
fi
hooks_dir="$git_dir/hooks"
hook="$hooks_dir/commit-msg"
marker="# Generated by rust-project-bootstrap install-commit-hooks."
mkdir -p "$hooks_dir"

if [[ -e $hook || -L $hook ]]; then
    if [[ -L $hook || ! -f $hook ]] || ! grep -Fqx "$marker" "$hook"; then
        echo "install-commit-hooks: refusing to overwrite existing hook: $hook" >&2
        exit 1
    fi
fi

tmp=$(mktemp "$hooks_dir/.commit-msg.XXXXXX")
trap 'rm -f "$tmp"' EXIT
cat >"$tmp" <<'HOOK'
#!/usr/bin/env bash
# Generated by rust-project-bootstrap install-commit-hooks.
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
"$repo_root/scripts/check-commit-message.sh" "${1:-}"
exec "$repo_root/scripts/run-staged-gates.sh"
HOOK
chmod +x "$tmp"
mv -f "$tmp" "$hook"
trap - EXIT

echo "Installed $hook"
