#!/usr/bin/env bash
# @okf-doc: /commit-hooks.md
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)
cd "$repo_root"

git rev-parse --absolute-git-dir >/dev/null 2>&1 || {
    echo "install-commit-hooks: repository is not initialized with git" >&2
    exit 1
}

if hooks_path=$(git config --get core.hooksPath); then
    echo "install-commit-hooks: core.hooksPath is already set to $hooks_path" >&2
    echo "refusing to bypass or replace the existing hook configuration" >&2
    exit 1
fi
if ! command -v prek >/dev/null 2>&1; then
    echo "install-commit-hooks: prek is missing; run scripts/setup-build-deps.sh" >&2
    exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
    echo "install-commit-hooks: python3 is required for local hook history" >&2
    exit 1
fi
prek validate-config prek.toml

# Git uses the common hooks directory in linked worktrees too.
hooks_dir=$(git rev-parse --path-format=absolute --git-path hooks)
hook="$hooks_dir/commit-msg"
bootstrap_marker="# Generated by rust-project-bootstrap install-commit-hooks."
prek_marker="# File generated by prek: https://github.com/j178/prek"

if [[ -e $hook || -L $hook ]]; then
    if [[ -L $hook || ! -f $hook ]] || \
        ! grep -Fqx -e "$bootstrap_marker" -e "$prek_marker" "$hook"; then
        echo "install-commit-hooks: refusing to overwrite existing hook: $hook" >&2
        exit 1
    fi
fi

# --overwrite also deletes this file; never discard a user's legacy hook.
if [[ -e $hook.legacy || -L $hook.legacy ]]; then
    echo "install-commit-hooks: refusing to remove existing hook: $hook.legacy" >&2
    exit 1
fi

# Prepare and instrument the native shim before replacing the shared hook.
mkdir -p "$hooks_dir"
staging=$(mktemp -d "$hooks_dir/.fathomable-hook.XXXXXX")
cleanup() {
    rm -f -- "$staging/hooks/commit-msg"
    if [[ -d $staging/hooks ]]; then
        rmdir -- "$staging/hooks"
    fi
    rmdir -- "$staging"
}
trap cleanup EXIT
prek install --config prek.toml --hook-type commit-msg --git-dir "$staging"
python3 scripts/commit-hook-history.py --instrument-shim "$staging/hooks/commit-msg"
mv -- "$staging/hooks/commit-msg" "$hook"
printf 'Installed observed commit-msg hook at %s\n' "$hook"
