#!/usr/bin/env python3
"""Exercise installed commit hooks without Cargo or the source checkout's Git state."""

import json
import os
from pathlib import Path
import shutil
import stat
import subprocess
import tempfile
import unittest


SOURCE_ROOT = Path(__file__).resolve().parent.parent
BOOTSTRAP_HOOK = """#!/usr/bin/env bash
# Generated by rust-project-bootstrap install-commit-hooks.
set -euo pipefail
repo_root=$(git rev-parse --show-toplevel)
"$repo_root/scripts/check-commit-message.sh" "$1"
exec "$repo_root/scripts/run-staged-gates.sh"
"""
FIXTURE_GATE = """#!/usr/bin/env bash
set -euo pipefail
exec python3 - "$@" <<'PY'
import json
import os
from pathlib import Path
import sys

root = Path(os.environ["FATHOMABLE_GATE_ROOT"])
files = {
    str(path.relative_to(root)): path.read_text()
    for path in sorted(root.rglob("*")) if path.is_file()
}
event = {
    "root": str(root), "files": files, "args": sys.argv[1:],
    "target": os.environ["CARGO_TARGET_DIR"],
    "index": os.environ.get("GIT_INDEX_FILE"),
}
with open(os.environ["FATHOMABLE_TEST_EVENTS"], "a") as log:
    log.write(json.dumps(event) + "\\n")
if files.get("payload.txt") == "invalid\\n":
    print("fixture gate: rejected staged payload")
    sys.exit(1)
print("fixture gate: accepted staged snapshot")
PY
"""


def inventory(root):
    """Compare contents and modes, not Git's mutable index stat cache."""
    result = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if relative.parts[0] == ".git":
            continue
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            content = os.readlink(path)
        elif stat.S_ISREG(mode):
            content = path.read_bytes()
        else:
            content = None
        result[str(relative)] = (mode, content)
    return result


class CommitHooks(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        for executable in ("git", "prek", "bash", "python3"):
            if shutil.which(executable) is None:
                raise RuntimeError(f"required executable is missing: {executable}")

    def setUp(self):
        scratch = SOURCE_ROOT / ".tmp"
        scratch.mkdir(exist_ok=True)
        self.workspace = tempfile.TemporaryDirectory(
            prefix="commit hooks ", dir=scratch
        )
        self.addCleanup(self.workspace.cleanup)
        self.base = Path(self.workspace.name)
        self.repo = self.base / "repo"
        self.repo.mkdir()
        self.log = self.base / "events.jsonl"
        self.snapshots = self.base / "snapshots"
        self.env = {
            key: value for key, value in os.environ.items()
            if not key.startswith(("GIT_", "PREK_", "FATHOMABLE_"))
            and key not in {
                "SKIP", "CARGO_TARGET_DIR", "BASH_ENV", "ENV", "CDPATH",
                "RUSTFLAGS", "RUSTDOCFLAGS",
            }
        }
        for variable, name in {
            "HOME": "home", "XDG_CONFIG_HOME": "config",
            "XDG_CACHE_HOME": "cache", "XDG_DATA_HOME": "data",
            "XDG_STATE_HOME": "state", "PREK_HOME": "prek",
            "GIT_TEMPLATE_DIR": "templates", "TMPDIR": "snapshots",
        }.items():
            directory = self.base / name
            directory.mkdir()
            self.env[variable] = str(directory)
        self.env.update({
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_CONFIG_SYSTEM": os.devnull,
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_TERMINAL_PROMPT": "0",
            "GIT_EDITOR": "true",
            "GIT_SEQUENCE_EDITOR": "true",
            "GIT_MERGE_AUTOEDIT": "no",
            "PREK_COLOR": "never",
            "FATHOMABLE_TEST_EVENTS": str(self.log),
            "TMP": str(self.snapshots),
            "TEMP": str(self.snapshots),
            "LC_ALL": "C",
        })
        self.git("init", "-q", "-b", "main")
        self.git("config", "user.name", "Hook Test")
        self.git("config", "user.email", "hook-test@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        self.git("config", "core.autocrlf", "false")
        for name in (
            "install-commit-hooks.sh", "check-commit-message.sh",
            "run-staged-gates.sh",
        ):
            destination = self.repo / "scripts" / name
            destination.parent.mkdir(exist_ok=True)
            shutil.copy2(SOURCE_ROOT / "scripts" / name, destination)
        shutil.copy2(SOURCE_ROOT / "prek.toml", self.repo / "prek.toml")
        self.write("scripts/gates.sh", FIXTURE_GATE, executable=True)
        self.write("payload.txt", "valid\n")
        self.write("keep.txt", "baseline\n")
        self.write(".gitignore", "ignored.dat\n")
        self.git("add", ".")
        self.git("commit", "-qm", "chore: initial fixture")
        self.hooks = Path(self.git(
            "rev-parse", "--path-format=absolute", "--git-path", "hooks"
        ).stdout.strip())
        self.hooks.mkdir(exist_ok=True)
        self.hook = self.hooks / "commit-msg"

    def run_command(self, *args, cwd=None, env=None, success=True):
        result = subprocess.run(
            args, cwd=cwd or self.repo, env=env or self.env,
            text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            timeout=30, check=False,
        )
        if success:
            self.assertEqual(result.returncode, 0, result.stdout)
        else:
            self.assertNotEqual(result.returncode, 0, result.stdout)
        return result

    def git(self, *args, **kwargs):
        return self.run_command("git", *args, **kwargs)

    def write(self, name, content, executable=False, repo=None):
        path = (repo or self.repo) / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        path.chmod(0o755 if executable else 0o644)
        return path

    def install(self, **kwargs):
        return self.run_command("bash", "scripts/install-commit-hooks.sh", **kwargs)

    def events(self):
        if not self.log.exists():
            return []
        return [json.loads(line) for line in self.log.read_text().splitlines()]

    def state(self, repo=None, env=None):
        return (
            self.git("ls-files", "--stage", "-z", cwd=repo, env=env).stdout,
            inventory(repo or self.repo),
        )

    def head(self, repo=None, env=None):
        return self.git("rev-parse", "HEAD", cwd=repo, env=env).stdout

    def assert_clean_snapshots(self):
        self.assertEqual(list(self.snapshots.iterdir()), [])
        for event in self.events():
            self.assertFalse(Path(event["root"]).exists())
            self.assertEqual(Path(event["root"]).parent, self.snapshots)
            self.assertEqual(event["args"], [])
            self.assertNotIn(".git", event["files"])

    def commit(self, message="test: exercise installed hooks", success=True,
               gates=1, repo=None, env=None):
        before = self.state(repo, env)
        head = self.head(repo, env)
        count = len(self.events())
        result = self.git(
            "commit", "--allow-empty", "-m", message, success=success,
            cwd=repo, env=env,
        )
        self.assertEqual(self.state(repo, env), before, result.stdout)
        if success:
            self.assertNotEqual(self.head(repo, env), head)
        else:
            self.assertEqual(self.head(repo, env), head)
        self.assertEqual(len(self.events()) - count, gates, result.stdout)
        self.assert_clean_snapshots()
        return result

    def assert_install_refused(self):
        before = inventory(self.hooks)
        self.install(success=False)
        self.assertEqual(inventory(self.hooks), before)

    def test_fresh_install_and_idempotent_reinstall(self):
        self.install()
        self.assertEqual(sorted(p.name for p in self.hooks.iterdir()), ["commit-msg"])
        self.assertTrue(os.access(self.hook, os.X_OK))
        before = inventory(self.hooks)
        self.install()
        self.assertEqual(inventory(self.hooks), before)
        self.commit()

    def test_bootstrap_migration_does_not_chain_or_duplicate_gate(self):
        self.hook.write_text(BOOTSTRAP_HOOK)
        self.hook.chmod(0o755)
        self.install()
        self.assertFalse((self.hooks / "commit-msg.legacy").exists())
        self.commit()

    def test_unknown_hook_is_preserved(self):
        self.hook.write_text("#!/bin/sh\n# a user's hook\nexit 0\n")
        self.hook.chmod(0o755)
        self.assert_install_refused()

    def test_symlink_hooks_are_preserved_even_with_recognized_target(self):
        target = self.base / "user-hook"
        target.write_text(BOOTSTRAP_HOOK)
        for destination in (target, self.base / "missing-hook"):
            with self.subTest(destination=destination.name):
                self.hook.symlink_to(destination)
                self.assert_install_refused()
                self.assertEqual(target.read_text(), BOOTSTRAP_HOOK)
                self.hook.unlink()

    def test_nonregular_hook_is_preserved(self):
        self.hook.mkdir()
        self.assert_install_refused()
        self.hook.rmdir()
        os.mkfifo(self.hook)
        self.assert_install_refused()

    def test_all_legacy_collisions_are_preserved(self):
        legacy = self.hooks / "commit-msg.legacy"
        for installed in (False, True):
            if installed:
                self.install()
            for kind in ("file", "directory", "symlink", "fifo"):
                with self.subTest(installed=installed, kind=kind):
                    if kind == "file":
                        legacy.write_text("user legacy hook\n")
                    elif kind == "directory":
                        legacy.mkdir()
                    elif kind == "symlink":
                        legacy.symlink_to(self.base / "missing-legacy")
                    else:
                        os.mkfifo(legacy)
                    self.assert_install_refused()
                    if kind == "directory":
                        legacy.rmdir()
                    else:
                        legacy.unlink()

    def test_configured_hooks_path_is_not_overridden(self):
        custom = self.base / "custom-hooks"
        custom.mkdir()
        (custom / "commit-msg").write_text("owned by user\n")
        for configured in (str(custom), ""):
            with self.subTest(path=configured):
                self.git("config", "core.hooksPath", configured)
                before = inventory(custom)
                self.assert_install_refused()
                self.assertEqual(inventory(custom), before)
                self.assertEqual(
                    self.git("config", "--get", "core.hooksPath").stdout.rstrip("\n"),
                    configured,
                )

    def test_missing_and_invalid_config_preserve_existing_hook(self):
        self.hook.write_text(BOOTSTRAP_HOOK)
        self.hook.chmod(0o755)
        self.write(".pre-commit-config.yaml", "repos: []\n")
        config = self.repo / "prek.toml"
        for content in (None, "repos = [\n"):
            with self.subTest(content=content):
                if content is None:
                    config.unlink()
                else:
                    config.write_text(content)
                self.assert_install_refused()

    def test_valid_commit_runs_one_complete_snapshot_gate(self):
        self.install()
        self.write("payload.txt", "staged change\n")
        self.git("add", "payload.txt")
        expected = set(self.git("ls-files", "-z").stdout.rstrip("\0").split("\0"))
        self.commit("feat(hooks): accept staged change")
        event = self.events()[0]
        self.assertEqual(set(event["files"]), expected)
        self.assertEqual(event["files"]["payload.txt"], "staged change\n")
        self.assertEqual(event["target"], str(self.repo / "target"))
        self.assertEqual(self.git("show", "HEAD:payload.txt").stdout, "staged change\n")

    def test_bad_messages_fail_before_expensive_gate(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        messages = (
            "not conventional",
            "feat: " + "x" * 67,
            "test: metadata\n\nCo-Authored-By: Copilot <bot@example.invalid>",
            "test: metadata\n\nco-authored-by: Claude <bot@example.invalid>",
            "test: metadata\n\nCo-Authored-By: Codex <bot@example.invalid>",
            "test: metadata\n\nCo-Authored-By: Tool <noreply@openai.com>",
            "test: metadata\n\nClaude-Session: fixture",
            "Merge branch 'topic'\n\nCo-Authored-By: Copilot <bot@example.invalid>",
        )
        for message in messages:
            with self.subTest(header=message.splitlines()[0]):
                self.commit(message, success=False, gates=0)

    def test_72_character_header_and_message_exemptions(self):
        self.install()
        messages = (
            "feat: " + "x" * 66,
            "Merge branch 'topic'", 'Revert "previous change"',
            "fixup! previous change", "squash! previous change",
            "amend! previous change",
            "test: human author\n\nCo-Authored-By: Human <human@example.invalid>",
        )
        self.assertEqual(len(messages[0]), 72)
        for message in messages:
            with self.subTest(header=message.splitlines()[0]):
                self.commit(message)

    def test_gate_failure_preserves_head_index_and_worktree(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        self.commit(success=False)
        self.assertEqual(self.events()[0]["files"]["payload.txt"], "invalid\n")

    def test_unstaged_fix_cannot_rescue_invalid_staged_payload(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        self.write("payload.txt", "valid\n")
        self.commit(success=False)
        self.assertEqual(self.events()[0]["files"]["payload.txt"], "invalid\n")

    def test_unstaged_untracked_and_ignored_data_do_not_contaminate_snapshot(self):
        self.install()
        self.write("payload.txt", "valid staged change\n")
        self.git("add", "payload.txt")
        self.write("payload.txt", "invalid\n")
        self.write("untracked.dat", "invalid\n")
        self.write("ignored.dat", "invalid\n")
        self.commit()
        files = self.events()[0]["files"]
        self.assertEqual(files["payload.txt"], "valid staged change\n")
        self.assertNotIn("untracked.dat", files)
        self.assertNotIn("ignored.dat", files)

    def test_staged_gate_script_wins_over_unstaged_script(self):
        self.install()
        self.write("scripts/gates.sh", "#!/bin/sh\nexit 99\n", executable=True)
        self.commit()
        self.assertEqual(self.events()[0]["files"]["scripts/gates.sh"], FIXTURE_GATE)

    def test_empty_and_deletion_only_commits_run_full_gate(self):
        self.install()
        self.commit("chore: empty commit")
        self.git("rm", "-q", "keep.txt")
        self.commit("chore: delete only")
        self.assertNotIn("keep.txt", self.events()[-1]["files"])

    def test_missing_or_nonexecutable_staged_gate_fails_closed(self):
        self.install()
        for missing in (True, False):
            with self.subTest(missing=missing):
                if missing:
                    self.git("rm", "-q", "scripts/gates.sh")
                else:
                    self.write("scripts/gates.sh", FIXTURE_GATE)
                    self.git("add", "scripts/gates.sh")
                self.commit(success=False, gates=0)

    def test_missing_commit_config_fails_closed(self):
        self.install()
        (self.repo / "prek.toml").unlink()
        self.commit(success=False, gates=0)

    def test_unstaged_commit_config_fails_closed_until_staged(self):
        self.install()
        self.write("payload.txt", "valid staged change\n")
        self.git("add", "payload.txt")
        config = self.repo / "prek.toml"
        config.write_text(config.read_text() + "\n# Valid but initially unstaged.\n")
        result = self.commit(success=False, gates=0)
        self.assertIn("not staged", result.stdout.lower())
        self.assertIn("prek.toml", result.stdout)
        self.git("add", "prek.toml")
        self.commit()
        self.assertEqual(self.events()[0]["files"]["prek.toml"], config.read_text())

    def test_linked_worktree_uses_shared_hook_and_own_index(self):
        self.install()
        linked = self.base / "linked worktree"
        self.git("worktree", "add", "-q", "-b", "linked", str(linked))
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        main = self.state()
        shared = inventory(self.hooks)
        self.install(cwd=linked)
        self.assertEqual(inventory(self.hooks), shared)
        self.assertEqual(
            Path(self.git(
                "rev-parse", "--path-format=absolute", "--git-path", "hooks",
                cwd=linked,
            ).stdout.strip()), self.hooks,
        )
        self.write("payload.txt", "valid linked change\n", repo=linked)
        self.git("add", "payload.txt", cwd=linked)
        self.commit(repo=linked)
        event = self.events()[0]
        self.assertEqual(event["files"]["payload.txt"], "valid linked change\n")
        self.assertEqual(event["target"], str(linked / "target"))
        self.assertEqual(self.state(), main)

    def test_alternate_index_is_respected_and_default_index_preserved(self):
        self.install()
        alternate = self.env | {"GIT_INDEX_FILE": str(self.base / "alternate-index")}
        self.git("read-tree", "HEAD", env=alternate)
        self.write("payload.txt", "alternate staged value\n")
        self.git("add", "payload.txt", env=alternate)
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        original = self.state()
        self.commit(env=alternate)
        self.assertEqual(self.state(), original)
        self.assertEqual(
            self.events()[0]["files"]["payload.txt"], "alternate staged value\n"
        )
        self.assertEqual(
            self.git("show", "HEAD:payload.txt").stdout, "alternate staged value\n"
        )

    def test_commit_only_uses_git_temporary_index(self):
        self.install()
        self.write("keep.txt", "unrelated staged change\n")
        self.git("add", "keep.txt")
        self.write("payload.txt", "selected worktree change\n")
        before = inventory(self.repo)
        unrelated = self.git("ls-files", "--stage", "keep.txt").stdout
        head = self.head()
        self.git("commit", "--only", "payload.txt", "-m", "fix: selected path")
        self.assertNotEqual(self.head(), head)
        self.assertEqual(inventory(self.repo), before)
        self.assertEqual(self.git("ls-files", "--stage", "keep.txt").stdout, unrelated)
        self.assertEqual(len(self.events()), 1)
        event = self.events()[0]
        self.assertEqual(event["files"]["payload.txt"], "selected worktree change\n")
        self.assertEqual(event["files"]["keep.txt"], "baseline\n")
        self.assertEqual(self.git("show", "HEAD:keep.txt").stdout, "baseline\n")
        self.assert_clean_snapshots()

    def test_non_fast_forward_merge_runs_gate(self):
        self.git("branch", "topic")
        self.write("main.txt", "main side\n")
        self.git("add", "main.txt")
        self.git("commit", "-qm", "test: main side")
        self.git("checkout", "-q", "topic")
        self.write("topic.txt", "topic side\n")
        self.git("add", "topic.txt")
        self.git("commit", "-qm", "test: topic side")
        self.git("checkout", "-q", "main")
        self.install()
        self.git("merge", "--no-ff", "--no-edit", "topic")
        parents = self.git("rev-list", "--parents", "-n", "1", "HEAD").stdout.split()
        self.assertEqual(len(parents), 3)
        self.assertEqual(len(self.events()), 1)
        files = self.events()[0]["files"]
        self.assertEqual(files["main.txt"], "main side\n")
        self.assertEqual(files["topic.txt"], "topic side\n")
        self.assert_clean_snapshots()

    def test_manual_stage_checks_index_without_autofixes(self):
        self.assert_direct_run("--stage", "manual", "--all-files")

    def test_default_run_checks_index_without_autofixes(self):
        self.assert_direct_run()

    def assert_direct_run(self, *selection):
        self.install()
        for staged, unstaged, success in (
            ("direct staged change\n", "invalid\n", True),
            ("invalid\n", "valid\n", False),
        ):
            with self.subTest(success=success):
                self.write("payload.txt", staged)
                self.git("add", "payload.txt")
                self.write("payload.txt", unstaged)
                before, head, count = self.state(), self.head(), len(self.events())
                self.run_command(
                    "prek", "run", "--config", "prek.toml",
                    *selection, success=success,
                )
                self.assertEqual(self.state(), before)
                self.assertEqual(self.head(), head)
                self.assertEqual(len(self.events()), count + 1)
                self.assertEqual(self.events()[-1]["files"]["payload.txt"], staged)
                self.assert_clean_snapshots()


if __name__ == "__main__":
    unittest.main()
