#!/usr/bin/env python3
"""Exercise real native prek hooks without Cargo or the source checkout's Git state."""

import json
import os
from pathlib import Path
import shutil
import signal
import stat
import subprocess
import tempfile
import time
import unittest


SOURCE_ROOT = Path(__file__).resolve().parent.parent
BOOTSTRAP_HOOK = """#!/usr/bin/env bash
# Generated by rust-project-bootstrap install-commit-hooks.
set -euo pipefail
repo_root=$(git rev-parse --show-toplevel)
"$repo_root/scripts/check-commit-message.sh" "$1"
exec "$repo_root/scripts/run-staged-gates.sh"
"""
GATE_COMMANDS = {
    "commit-hooks": ["python3", "scripts/test-commit-hooks.py"],
    "fmt": ["cargo", "fmt", "--check"],
    "clippy": [
        "cargo", "clippy", "--all-targets", "--all-features",
        "--", "-D", "warnings", "-F", "unsafe-code",
    ],
    "nextest": ["cargo", "nextest", "run", "--all-targets", "--all-features"],
    "doctest": ["scripts/test-doctests.sh"],
    "okf": ["python3", "scripts/okf-lint.py", "--repo-root", ".", "docs"],
    "links": [
        "lychee", "--offline", "--no-progress", "docs", "README.md",
        "CONTRIBUTING.md", "AGENTS.md",
        ".agents/skills/open-knowledge-format/SKILL.md",
        ".agents/skills/fathomable-threatmodel/SKILL.md",
    ],
    "boundaries": ["scripts/check-boundaries.sh"],
    "rustdoc": ["cargo", "doc", "--no-deps", "--all-features"],
    "public-api": ["scripts/check-public-api.sh"],
    "audit": ["cargo", "audit"],
    "deny": ["cargo", "deny", "check"],
    "licenses": ["scripts/check-licenses.sh"],
}
for gate in ("fmt", "clippy", "rustdoc"):
    GATE_COMMANDS[gate] = [
        "python3", "scripts/rust-toolchain.py", "release", *GATE_COMMANDS[gate],
    ]
GATE_IDS = list(GATE_COMMANDS)
FIXTURE_SCRIPTS = (
    "scripts/test-commit-hooks.py", "scripts/test-doctests.sh",
    "scripts/okf-lint.py", "scripts/check-boundaries.sh",
    "scripts/check-public-api.sh", "scripts/check-licenses.sh",
    "scripts/rust-toolchain.py",
)
# Keep the production config unchanged: only the programs it invokes are fixtures.
FIXTURE_GATE = """#!/usr/bin/env python3
import json
import os
from pathlib import Path
import sys
import time

program = Path(sys.argv[0]).name
if program == "cargo":
    hook = {
        "fmt": "fmt", "clippy": "clippy", "nextest": "nextest",
        "doc": "rustdoc", "audit": "audit", "deny": "deny",
    }[sys.argv[1]]
    command = [program, *sys.argv[1:]]
elif program == "lychee":
    hook = "links"
    command = [program, *sys.argv[1:]]
elif program == "rust-toolchain.py":
    assert sys.argv[1:3] == ["release", "cargo"]
    hook = {"fmt": "fmt", "clippy": "clippy", "doc": "rustdoc"}[sys.argv[3]]
    command = ["python3", *json.loads(os.environ["FATHOMABLE_TEST_PYTHON_ARGS"])]
else:
    hook = {
        "test-commit-hooks.py": "commit-hooks",
        "test-doctests.sh": "doctest", "okf-lint.py": "okf",
        "check-boundaries.sh": "boundaries",
        "check-public-api.sh": "public-api",
        "check-licenses.sh": "licenses",
    }[program]
    command = sys.argv[:]
    if Path(command[0]).is_absolute():
        command[0] = str(Path(command[0]).relative_to(Path.cwd()))
    if program.endswith(".py"):
        command = ["python3", *json.loads(os.environ["FATHOMABLE_TEST_PYTHON_ARGS"])]

root = Path.cwd()
files = {}
for directory, children, names in os.walk(root):
    children[:] = sorted(name for name in children if name not in {".git", ".tmp"})
    for name in sorted(names):
        path = Path(directory) / name
        if name != ".git":
            files[str(path.relative_to(root))] = path.read_text()
event = {
    "hook": hook, "command": command, "root": str(root), "files": files,
    "git": (root / ".git").exists(),
    "target": os.environ.get("CARGO_TARGET_DIR"),
    "rustdocflags": os.environ.get("RUSTDOCFLAGS"),
    "index": os.environ.get("GIT_INDEX_FILE"),
}
with open(os.environ["FATHOMABLE_TEST_EVENTS"], "a") as log:
    log.write(json.dumps(event) + "\\n")
if os.environ.get("FATHOMABLE_TEST_DELAY_HOOK") == hook:
    time.sleep(0.08)
if os.environ.get("FATHOMABLE_TEST_WAIT_HOOK") == hook:
    (root / ".tmp" / "phase-ready").touch()
    time.sleep(30)
if (os.environ.get("FATHOMABLE_TEST_FAIL_HOOK") == hook
        or (hook == "commit-hooks" and files.get("payload.txt") == "invalid\\n")):
    if os.environ.get("FATHOMABLE_TEST_LARGE_ERROR"):
        print("earliest diagnostic " + "x" * 70000)
    print("fixture gate: rejected " + hook)
    sys.exit(1)
print("fixture gate: accepted " + hook)
"""
FIXTURE_PYTHON = """import json
import os
import sys

os.environ["FATHOMABLE_TEST_PYTHON_ARGS"] = json.dumps(sys.argv[1:])
os.execv(sys.executable, [sys.executable, *sys.argv[1:]])
"""


def inventory(root):
    """Compare contents and modes, not Git's mutable index stat cache."""
    result = {}
    for path in sorted(root.rglob("*")):
        relative = path.relative_to(root)
        if relative.parts[0] in {".git", ".tmp"}:
            continue
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            content = os.readlink(path)
        elif stat.S_ISREG(mode):
            content = path.read_bytes()
        else:
            content = None
        result[str(relative)] = (mode, content)
    return result


class CommitHooks(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        for executable in ("git", "prek", "bash", "python3"):
            if shutil.which(executable) is None:
                raise RuntimeError(f"required executable is missing: {executable}")

    def setUp(self):
        scratch = SOURCE_ROOT / ".tmp"
        scratch.mkdir(exist_ok=True)
        self.workspace = tempfile.TemporaryDirectory(
            prefix="commit hooks ", dir=scratch
        )
        self.addCleanup(self.workspace.cleanup)
        self.base = Path(self.workspace.name)
        self.repo = self.base / "repo"
        self.repo.mkdir()
        self.log = self.base / "events.jsonl"
        self.runtime = self.base / "runtime"
        self.env = {
            key: value for key, value in os.environ.items()
            if not key.startswith(("GIT_", "PREK_", "FATHOMABLE_"))
            and key not in {
                "SKIP", "CARGO_TARGET_DIR", "BASH_ENV", "ENV", "CDPATH",
                "RUSTFLAGS", "RUSTDOCFLAGS",
            }
        }
        for variable, name in {
            "HOME": "home", "XDG_CONFIG_HOME": "config",
            "XDG_CACHE_HOME": "cache", "XDG_DATA_HOME": "data",
            "XDG_STATE_HOME": "state", "PREK_HOME": "prek",
            "GIT_TEMPLATE_DIR": "templates", "TMPDIR": "runtime",
        }.items():
            directory = self.base / name
            directory.mkdir()
            self.env[variable] = str(directory)
        self.env.update({
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_CONFIG_SYSTEM": os.devnull,
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_TERMINAL_PROMPT": "0",
            "GIT_EDITOR": "true",
            "GIT_SEQUENCE_EDITOR": "true",
            "GIT_MERGE_AUTOEDIT": "no",
            "PREK_COLOR": "never",
            "FATHOMABLE_TEST_EVENTS": str(self.log),
            "TMP": str(self.runtime),
            "TEMP": str(self.runtime),
            "PYTHONDONTWRITEBYTECODE": "1",
            "LC_ALL": "C",
        })
        binaries = self.base / "bin"
        for name in ("cargo", "lychee"):
            self.write(name, FIXTURE_GATE, executable=True, repo=binaries)
        self.write(
            "python3", "#!" + shutil.which("python3") + "\n" + FIXTURE_PYTHON,
            executable=True, repo=binaries,
        )
        self.env["PATH"] = str(binaries) + os.pathsep + self.env["PATH"]
        self.git("init", "-q", "-b", "main")
        self.git("config", "user.name", "Hook Test")
        self.git("config", "user.email", "hook-test@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        self.git("config", "core.autocrlf", "false")
        for name in (
            "install-commit-hooks.sh", "check-commit-message.sh", "commit-hook-history.py",
        ):
            destination = self.repo / "scripts" / name
            destination.parent.mkdir(exist_ok=True)
            shutil.copy2(SOURCE_ROOT / "scripts" / name, destination)
        shutil.copy2(SOURCE_ROOT / "prek.toml", self.repo / "prek.toml")
        for name in FIXTURE_SCRIPTS:
            self.write(name, FIXTURE_GATE, executable=True)
        self.write("payload.txt", "valid\n")
        self.write("keep.txt", "baseline\n")
        self.write(".gitignore", "ignored.dat\n.tmp/\n")
        self.git("add", ".")
        self.git("commit", "-qm", "chore: initial fixture")
        self.hooks = Path(self.git(
            "rev-parse", "--path-format=absolute", "--git-path", "hooks"
        ).stdout.strip())
        self.hooks.mkdir(exist_ok=True)
        self.hook = self.hooks / "commit-msg"

    def run_command(self, *args, cwd=None, env=None, success=True):
        result = subprocess.run(
            args, cwd=cwd or self.repo, env=env or self.env,
            text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            timeout=30, check=False,
        )
        if success:
            self.assertEqual(result.returncode, 0, result.stdout)
        else:
            self.assertNotEqual(result.returncode, 0, result.stdout)
        return result

    def git(self, *args, **kwargs):
        return self.run_command("git", *args, **kwargs)

    def write(self, name, content, executable=False, repo=None):
        path = (repo or self.repo) / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        path.chmod(0o755 if executable else 0o644)
        return path

    def install(self, **kwargs):
        return self.run_command("bash", "scripts/install-commit-hooks.sh", **kwargs)

    def events(self):
        if not self.log.exists():
            return []
        return [json.loads(line) for line in self.log.read_text().splitlines()]

    def history(self, repo=None, kind="output"):
        directory = (repo or self.repo) / ".tmp/commit-hook-history"
        return sorted(directory.glob(f"*.{kind}.log"))

    def state(self, repo=None, env=None):
        return (
            self.git("ls-files", "--stage", "-z", cwd=repo, env=env).stdout,
            inventory(repo or self.repo),
        )

    def head(self, repo=None, env=None):
        return self.git("rev-parse", "HEAD", cwd=repo, env=env).stdout

    def assert_gates(self, events, gates=None, repo=None, env=None):
        expected = GATE_IDS if gates is None else gates
        self.assertEqual([event["hook"] for event in events], expected)
        environment = self.env if env is None else env
        for event in events:
            self.assertEqual(event["command"], GATE_COMMANDS[event["hook"]])
            self.assertEqual(Path(event["root"]), repo or self.repo)
            self.assertTrue(event["git"])
            self.assertEqual(event["target"], environment.get("CARGO_TARGET_DIR"))
            self.assertEqual(
                event["rustdocflags"],
                "-Dwarnings" if event["hook"] == "rustdoc"
                else environment.get("RUSTDOCFLAGS"),
            )

    def commit(self, message="test: exercise installed hooks", success=True,
               gates=None, repo=None, env=None):
        before = self.state(repo, env)
        head = self.head(repo, env)
        count = len(self.events())
        result = self.git(
            "commit", "--allow-empty", "-m", message, success=success,
            cwd=repo, env=env,
        )
        self.assertEqual(self.state(repo, env), before, result.stdout)
        if success:
            self.assertNotEqual(self.head(repo, env), head)
        else:
            self.assertEqual(self.head(repo, env), head)
        self.assert_gates(self.events()[count:], gates, repo, env)
        return result

    def assert_install_refused(self):
        before = inventory(self.hooks)
        self.install(success=False)
        self.assertEqual(inventory(self.hooks), before)

    def test_fresh_install_and_idempotent_reinstall(self):
        self.install()
        self.assertEqual(sorted(p.name for p in self.hooks.iterdir()), ["commit-msg"])
        self.assertTrue(os.access(self.hook, os.X_OK))
        before = inventory(self.hooks)
        self.install()
        self.assertEqual(inventory(self.hooks), before)
        self.commit()

    def test_bootstrap_migration_does_not_chain_or_duplicate_gate(self):
        self.hook.write_text(BOOTSTRAP_HOOK)
        self.hook.chmod(0o755)
        self.install()
        self.assertFalse((self.hooks / "commit-msg.legacy").exists())
        self.commit()

    def test_observer_install_failure_preserves_the_installed_hook(self):
        self.install()
        self.write("scripts/commit-hook-history.py", "raise SystemExit(91)\n")
        self.assert_install_refused()

    def test_other_hooks_are_untouched(self):
        for name in ("pre-commit", "pre-push", "prepare-commit-msg"):
            hook = self.hooks / name
            hook.write_text("#!/bin/sh\n# user-owned hook\nexit 0\n")
            hook.chmod(0o755)
        before = inventory(self.hooks)
        self.install()
        after = inventory(self.hooks)
        del after["commit-msg"]
        self.assertEqual(after, before)

    def test_unknown_hook_is_preserved(self):
        self.hook.write_text("#!/bin/sh\n# a user's hook\nexit 0\n")
        self.hook.chmod(0o755)
        self.assert_install_refused()

    def test_symlink_hooks_are_preserved_even_with_recognized_target(self):
        target = self.base / "user-hook"
        target.write_text(BOOTSTRAP_HOOK)
        for destination in (target, self.base / "missing-hook"):
            with self.subTest(destination=destination.name):
                self.hook.symlink_to(destination)
                self.assert_install_refused()
                self.assertEqual(target.read_text(), BOOTSTRAP_HOOK)
                self.hook.unlink()

    def test_nonregular_hook_is_preserved(self):
        self.hook.mkdir()
        self.assert_install_refused()
        self.hook.rmdir()
        os.mkfifo(self.hook)
        self.assert_install_refused()

    def test_all_legacy_collisions_are_preserved(self):
        legacy = self.hooks / "commit-msg.legacy"
        for installed in (False, True):
            if installed:
                self.install()
            for kind in ("file", "directory", "symlink", "fifo"):
                with self.subTest(installed=installed, kind=kind):
                    if kind == "file":
                        legacy.write_text("user legacy hook\n")
                    elif kind == "directory":
                        legacy.mkdir()
                    elif kind == "symlink":
                        legacy.symlink_to(self.base / "missing-legacy")
                    else:
                        os.mkfifo(legacy)
                    self.assert_install_refused()
                    if kind == "directory":
                        legacy.rmdir()
                    else:
                        legacy.unlink()

    def test_configured_hooks_path_is_not_overridden(self):
        custom = self.base / "custom-hooks"
        custom.mkdir()
        (custom / "commit-msg").write_text("owned by user\n")
        for configured in (str(custom), ""):
            with self.subTest(path=configured):
                self.git("config", "core.hooksPath", configured)
                before = inventory(custom)
                self.assert_install_refused()
                self.assertEqual(inventory(custom), before)
                self.assertEqual(
                    self.git("config", "--get", "core.hooksPath").stdout.rstrip("\n"),
                    configured,
                )

    def test_missing_and_invalid_config_preserve_existing_hook(self):
        self.hook.write_text(BOOTSTRAP_HOOK)
        self.hook.chmod(0o755)
        self.write(".pre-commit-config.yaml", "repos: []\n")
        config = self.repo / "prek.toml"
        for content in (None, "repos = [\n"):
            with self.subTest(content=content):
                if content is None:
                    config.unlink()
                else:
                    config.write_text(content)
                self.assert_install_refused()

    def test_valid_commit_runs_each_production_gate_once_in_order(self):
        self.install()
        self.write("payload.txt", "staged change\n")
        self.git("add", "payload.txt")
        expected = set(self.git("ls-files", "-z").stdout.rstrip("\0").split("\0"))
        self.commit("feat(hooks): accept staged change")
        for event in self.events():
            self.assertEqual(set(event["files"]), expected)
            self.assertEqual(event["files"]["payload.txt"], "staged change\n")
        self.assertEqual(self.git("show", "HEAD:payload.txt").stdout, "staged change\n")

    def test_history_records_each_attempt_and_native_phase_timings(self):
        self.install()
        self.write("payload.txt", "staged change\n")
        self.git("add", "payload.txt")
        for _ in range(2):
            self.commit(env=self.env | {"FATHOMABLE_TEST_DELAY_HOOK": "fmt"})
        logs, traces = self.history(), self.history(kind="prek")
        self.assertEqual(len(logs), 2)
        self.assertEqual(len(traces), 2)
        for log, trace in zip(logs, traces, strict=True):
            self.assertRegex(log.name, r"^\d{8}T\d{6}\.\d{6}Z-.+\.output\.log$")
            text = log.read_text()
            self.assertIn(f"worktree={self.repo}", text)
            self.assertIn("triggered_at=", text)
            self.assertIn("finished_at=", text)
            self.assertIn("exit_code=0\nexit_reason=passed", text)
            duration = float(text.split("duration_seconds=")[-1].splitlines()[0])
            self.assertGreaterEqual(duration, 0.08)
            native = trace.read_text()
            self.assertIn("DEBUG prek: 0.5.3", native)
            for hook in ["commit-message", *GATE_IDS]:
                self.assertIn(f"run{{hook_id={hook} language=system}}: close time.busy=", native)
            for path in (log, trace):
                self.assertEqual(stat.S_IMODE(path.stat().st_mode), 0o600)
                self.git("check-ignore", str(path))

    def test_history_records_message_rejection_before_any_gate(self):
        self.install()
        self.commit("invalid subject", success=False, gates=[])
        text = self.history()[-1].read_text()
        self.assertIn("- hook id: commit-message", text)
        self.assertIn("exit_code=1\nexit_reason=failed", text)
        self.assertIn("does not follow Conventional Commits", text)
        self.assertNotIn("hook_id=fmt", self.history(kind="prek")[-1].read_text())

    def test_history_retains_full_failure_details(self):
        self.install()
        self.commit(
            success=False, gates=["commit-hooks", "fmt"],
            env=self.env | {
                "FATHOMABLE_TEST_FAIL_HOOK": "fmt", "FATHOMABLE_TEST_LARGE_ERROR": "1",
            },
        )
        text = self.history()[-1].read_text()
        self.assertIn("- hook id: fmt", text)
        self.assertIn("- exit code: 1", text)
        self.assertIn("exit_code=1\nexit_reason=failed", text)
        self.assertIn("fixture gate: rejected fmt", text)
        self.assertIn("earliest diagnostic", text)

    def test_history_records_native_setup_errors_without_inventing_phases(self):
        self.install()
        config = self.repo / "prek.toml"
        config.write_text(config.read_text() + "\n# unstaged config\n")
        self.commit(success=False, gates=[])
        text = self.history()[-1].read_text()
        self.assertIn("not staged", text.lower())
        self.assertIn("exit_reason=failed", text)
        self.assertNotIn("run{hook_id=", self.history(kind="prek")[-1].read_text())

    def test_logging_failure_warns_without_changing_gate_results(self):
        self.install()
        self.write(".tmp/commit-hook-history", "not a directory\n")
        result = self.commit()
        self.assertIn("cannot create logs", result.stdout)
        result = self.commit(
            success=False, gates=["commit-hooks"],
            env=self.env | {"FATHOMABLE_TEST_FAIL_HOOK": "commit-hooks"},
        )
        self.assertIn("cannot create logs", result.stdout)
        self.assertIn("fixture gate: rejected commit-hooks", result.stdout)

    def test_observer_forwards_termination_and_records_interruption(self):
        self.install()
        process = subprocess.Popen(
            ["git", "commit", "--allow-empty", "-m", "test: interrupted hook"],
            cwd=self.repo, env=self.env | {"FATHOMABLE_TEST_WAIT_HOOK": "fmt"},
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        )
        observer_pid = None
        try:
            ready = self.repo / ".tmp/phase-ready"
            deadline = time.monotonic() + 10
            while not ready.exists() and time.monotonic() < deadline:
                self.assertIsNone(process.poll())
                time.sleep(0.02)
            self.assertTrue(ready.exists(), "fixture phase did not start")
            text = self.history()[0].read_text()
            observer_pid = int(text.split("observer_pid=")[1].splitlines()[0])
            os.kill(observer_pid, signal.SIGTERM)
            output, _ = process.communicate(timeout=10)
            self.assertNotEqual(process.returncode, 0, output.decode())
            text = self.history()[-1].read_text()
            self.assertIn("finished_at=", text)
            self.assertIn("exit_reason=SIGTERM", text)
            self.assertNotIn("exit_code=0\n", text)
        finally:
            if process.poll() is None:
                if observer_pid is not None:
                    os.kill(observer_pid, signal.SIGTERM)
                process.terminate()
                process.communicate(timeout=10)

    def test_native_gates_preserve_environment_except_rustdoc_flags(self):
        self.install()
        self.commit(env=self.env | {
            "CARGO_TARGET_DIR": str(self.base / "custom-target"),
            "RUSTDOCFLAGS": "--cfg fixture",
        })

    def test_bad_messages_fail_before_expensive_gate(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        messages = (
            "not conventional",
            "feat: " + "x" * 67,
            "test: metadata\n\nCo-Authored-By: Copilot <bot@example.invalid>",
            "test: metadata\n\nco-authored-by: Claude <bot@example.invalid>",
            "test: metadata\n\nCo-Authored-By: Codex <bot@example.invalid>",
            "test: metadata\n\nCo-Authored-By: Tool <noreply@openai.com>",
            "test: metadata\n\nClaude-Session: fixture",
            "Merge branch 'topic'\n\nCo-Authored-By: Copilot <bot@example.invalid>",
        )
        for message in messages:
            with self.subTest(header=message.splitlines()[0]):
                self.commit(message, success=False, gates=[])

    def test_72_character_header_and_message_exemptions(self):
        self.install()
        messages = (
            "feat: " + "x" * 66,
            "Merge branch 'topic'", 'Revert "previous change"',
            "fixup! previous change", "squash! previous change",
            "amend! previous change",
            "test: human author\n\nCo-Authored-By: Human <human@example.invalid>",
        )
        self.assertEqual(len(messages[0]), 72)
        for message in messages:
            with self.subTest(header=message.splitlines()[0]):
                self.commit(message)

    def test_gate_failure_preserves_head_index_and_worktree(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        self.commit(success=False, gates=["commit-hooks"])
        self.assertEqual(self.events()[0]["files"]["payload.txt"], "invalid\n")

    def test_every_gate_failure_stops_later_gates_and_blocks_commit(self):
        self.install()
        for position, hook in enumerate(GATE_IDS):
            with self.subTest(hook=hook):
                result = self.commit(
                    success=False, gates=GATE_IDS[:position + 1],
                    env=self.env | {"FATHOMABLE_TEST_FAIL_HOOK": hook},
                )
                self.assertIn("fixture gate: rejected " + hook, result.stdout)

    def test_unstaged_fix_cannot_rescue_invalid_staged_payload(self):
        self.install()
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        self.write("payload.txt", "valid\n")
        self.commit(success=False, gates=["commit-hooks"])
        self.assertEqual(self.events()[0]["files"]["payload.txt"], "invalid\n")

    def test_native_stash_hides_tracked_edits_but_not_untracked_or_ignored_files(self):
        self.install()
        self.write("payload.txt", "valid staged change\n")
        self.git("add", "payload.txt")
        self.write("payload.txt", "invalid\n")
        self.write("untracked.dat", "invalid\n")
        self.write("ignored.dat", "invalid\n")
        self.commit()
        for event in self.events():
            files = event["files"]
            self.assertEqual(files["payload.txt"], "valid staged change\n")
            self.assertEqual(files["untracked.dat"], "invalid\n")
            self.assertEqual(files["ignored.dat"], "invalid\n")

    def test_staged_gate_script_wins_over_unstaged_script(self):
        self.install()
        name = "scripts/test-commit-hooks.py"
        staged = FIXTURE_GATE + "\n# staged fixture version\n"
        self.write(name, staged, executable=True)
        self.git("add", name)
        self.write(name, "raise SystemExit(99)\n", executable=True)
        self.commit()
        for event in self.events():
            self.assertEqual(event["files"][name], staged)

    def test_empty_deletion_and_docs_only_commits_run_every_gate(self):
        self.install()
        self.commit("chore: empty commit")
        self.git("rm", "-q", "keep.txt")
        self.commit("chore: delete only")
        self.assertNotIn("keep.txt", self.events()[-1]["files"])
        self.write("docs/example.md", "# Documentation only\n")
        self.git("add", "docs/example.md")
        self.commit("docs: documentation only")

    def test_missing_native_gate_script_fails_closed(self):
        self.install()
        name = "scripts/check-boundaries.sh"
        self.git("rm", "-q", name)
        self.commit(
            success=False, gates=GATE_IDS[:GATE_IDS.index("boundaries")]
        )

    def test_native_prek_can_run_nonexecutable_script_using_its_shebang(self):
        self.install()
        name = "scripts/check-boundaries.sh"
        self.write(name, FIXTURE_GATE)
        self.git("add", name)
        self.commit()

    def test_missing_commit_config_fails_closed(self):
        self.install()
        (self.repo / "prek.toml").unlink()
        self.write(".pre-commit-config.yaml", "repos: []\n")
        self.commit(success=False, gates=[])

    def test_unstaged_config_is_refused_except_with_all_files(self):
        self.install()
        self.write("payload.txt", "valid staged change\n")
        self.git("add", "payload.txt")
        config = self.repo / "prek.toml"
        config.write_text(config.read_text() + "\n# Valid but initially unstaged.\n")
        result = self.commit(success=False, gates=[])
        self.assertIn("not staged", result.stdout.lower())
        self.assertIn("prek.toml", result.stdout)
        for selection in ((), ("--stage", "manual")):
            with self.subTest(selection=selection):
                before = self.state()
                result = self.run_command(
                    "prek", "run", "--config", "prek.toml", *selection,
                    success=False,
                )
                self.assertIn("not staged", result.stdout.lower())
                self.assertEqual(self.state(), before)
                self.assertEqual(self.events(), [])
        before = self.state()
        self.run_command("prek", "run", "--config", "prek.toml", "--all-files")
        self.assertEqual(self.state(), before)
        self.assert_gates(self.events())
        self.assertEqual(self.events()[0]["files"]["prek.toml"], config.read_text())
        self.git("add", "prek.toml")
        self.commit()

    def test_linked_worktree_uses_shared_hook_and_own_index(self):
        self.install()
        linked = self.base / "linked worktree"
        self.git("worktree", "add", "-q", "-b", "linked", str(linked))
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        main = self.state()
        shared = inventory(self.hooks)
        self.install(cwd=linked)
        self.assertEqual(inventory(self.hooks), shared)
        self.assertEqual(
            Path(self.git(
                "rev-parse", "--path-format=absolute", "--git-path", "hooks",
                cwd=linked,
            ).stdout.strip()), self.hooks,
        )
        self.write("payload.txt", "valid linked change\n", repo=linked)
        self.git("add", "payload.txt", cwd=linked)
        self.commit(repo=linked)
        event = self.events()[0]
        self.assertEqual(event["files"]["payload.txt"], "valid linked change\n")
        self.assertEqual(self.state(), main)
        self.assertEqual(self.history(), [])
        self.assertIn(f"worktree={linked}", self.history(linked)[-1].read_text())

    def test_alternate_index_is_respected_and_default_index_preserved(self):
        self.install()
        alternate = self.env | {"GIT_INDEX_FILE": str(self.base / "alternate-index")}
        self.git("read-tree", "HEAD", env=alternate)
        self.write("payload.txt", "alternate staged value\n")
        self.git("add", "payload.txt", env=alternate)
        self.write("payload.txt", "invalid\n")
        self.git("add", "payload.txt")
        original = self.state()
        self.commit(env=alternate)
        self.assertEqual(self.state(), original)
        self.assertEqual(
            self.events()[0]["files"]["payload.txt"], "alternate staged value\n"
        )
        self.assertEqual(
            self.git("show", "HEAD:payload.txt").stdout, "alternate staged value\n"
        )

    def test_commit_only_uses_git_temporary_index(self):
        self.install()
        self.write("keep.txt", "unrelated staged change\n")
        self.git("add", "keep.txt")
        self.write("payload.txt", "selected worktree change\n")
        before = inventory(self.repo)
        unrelated = self.git("ls-files", "--stage", "keep.txt").stdout
        head = self.head()
        self.git("commit", "--only", "payload.txt", "-m", "fix: selected path")
        self.assertNotEqual(self.head(), head)
        self.assertEqual(inventory(self.repo), before)
        self.assertEqual(self.git("ls-files", "--stage", "keep.txt").stdout, unrelated)
        self.assert_gates(self.events())
        event = self.events()[0]
        self.assertEqual(event["files"]["payload.txt"], "selected worktree change\n")
        self.assertEqual(event["files"]["keep.txt"], "baseline\n")
        self.assertEqual(self.git("show", "HEAD:keep.txt").stdout, "baseline\n")

    def test_non_fast_forward_merge_runs_gate(self):
        self.git("branch", "topic")
        self.write("main.txt", "main side\n")
        self.git("add", "main.txt")
        self.git("commit", "-qm", "test: main side")
        self.git("checkout", "-q", "topic")
        self.write("topic.txt", "topic side\n")
        self.git("add", "topic.txt")
        self.git("commit", "-qm", "test: topic side")
        self.git("checkout", "-q", "main")
        self.install()
        self.git("merge", "--no-ff", "--no-edit", "topic")
        parents = self.git("rev-list", "--parents", "-n", "1", "HEAD").stdout.split()
        self.assertEqual(len(parents), 3)
        self.assert_gates(self.events())
        files = self.events()[0]["files"]
        self.assertEqual(files["main.txt"], "main side\n")
        self.assertEqual(files["topic.txt"], "topic side\n")

    def test_manual_stage_checks_index_without_autofixes(self):
        self.assert_direct_run("--stage", "manual")

    def test_default_run_checks_index_without_autofixes(self):
        self.assert_direct_run()

    def test_explicit_pre_commit_stage_checks_index(self):
        self.assert_direct_run("--stage", "pre-commit")

    def test_all_files_checks_current_checkout_without_stashing(self):
        self.assert_direct_run("--all-files", all_files=True)

    def test_manual_all_files_checks_current_checkout_without_stashing(self):
        self.assert_direct_run("--stage", "manual", "--all-files", all_files=True)

    def test_each_native_gate_can_be_selected_independently(self):
        self.install()
        for hook in GATE_IDS:
            with self.subTest(hook=hook):
                before, count = self.state(), len(self.events())
                self.run_command(
                    "prek", "run", "--config", "prek.toml", hook, "--all-files",
                )
                self.assertEqual(self.state(), before)
                self.assert_gates(self.events()[count:], [hook])

    def test_plain_and_manual_runs_without_staged_paths_still_run_every_gate(self):
        self.install()
        for selection in ((), ("--stage", "manual")):
            with self.subTest(selection=selection):
                before, count = self.state(), len(self.events())
                self.run_command(
                    "prek", "run", "--config", "prek.toml", *selection,
                )
                self.assertEqual(self.state(), before)
                self.assert_gates(self.events()[count:])

    def assert_direct_run(self, *selection, all_files=False):
        self.install()
        for staged, unstaged in (
            ("direct staged change\n", "invalid\n"),
            ("invalid\n", "valid\n"),
        ):
            checked = unstaged if all_files else staged
            success = checked != "invalid\n"
            with self.subTest(success=success):
                self.write("payload.txt", staged)
                self.git("add", "payload.txt")
                self.write("payload.txt", unstaged)
                before, head, count = self.state(), self.head(), len(self.events())
                self.run_command(
                    "prek", "run", "--config", "prek.toml",
                    *selection, success=success,
                )
                self.assertEqual(self.state(), before)
                self.assertEqual(self.head(), head)
                self.assertEqual(self.history(), [])
                events = self.events()[count:]
                self.assert_gates(
                    events, GATE_IDS if success else ["commit-hooks"],
                )
                for event in events:
                    self.assertEqual(event["files"]["payload.txt"], checked)


if __name__ == "__main__":
    unittest.main()
